# Generated by Django 5.2.1 on 2025-05-24 11:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('guest', 'Гость'), ('client', 'Клиент'), ('service', 'Сервисная организация'), ('manager', 'Менеджер')], default='guest', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Зав. № машины')),
                ('engine_serial', models.CharField(max_length=50, verbose_name='Зав. № двигателя')),
                ('transmission_serial', models.CharField(max_length=50, verbose_name='Зав. № трансмиссии')),
                ('drive_axle_serial', models.CharField(max_length=50, verbose_name='Зав. № ведущего моста')),
                ('steer_axle_serial', models.CharField(max_length=50, verbose_name='Зав. № управляемого моста')),
                ('contract', models.CharField(blank=True, max_length=200, verbose_name='Договор поставки №, дата')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('client', models.CharField(max_length=200, verbose_name='Покупатель')),
                ('consignee', models.CharField(max_length=200, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=300, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(verbose_name='Комплектация (доп. опции)')),
                ('client_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_machines', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('drive_axle_model', models.ForeignKey(blank=True, limit_choices_to={'entity_name': 'Модель ведущего моста'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_drive_axle_model', to='core.directory', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(blank=True, limit_choices_to={'entity_name': 'Модель двигателя'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_engine_model', to='core.directory', verbose_name='Модель двигателя')),
                ('model', models.ForeignKey(blank=True, limit_choices_to={'entity_name': 'Модель техники'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_model', to='core.directory', verbose_name='Модель техники')),
                ('service_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_machines', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('steer_axle_model', models.ForeignKey(blank=True, limit_choices_to={'entity_name': 'Модель управляемого моста'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_steer_axle_model', to='core.directory', verbose_name='Модель управляемого моста')),
                ('transmission_model', models.ForeignKey(blank=True, limit_choices_to={'entity_name': 'Модель трансмиссии'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_transmission_model', to='core.directory', verbose_name='Модель трансмиссии')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('used_parts', models.TextField(blank=True, verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.IntegerField(verbose_name='Время простоя техники (дни)')),
                ('failed_unit', models.ForeignKey(blank=True, limit_choices_to={'entity_name': 'Узел отказа'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_failed_unit', to='core.directory', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(blank=True, limit_choices_to={'entity_name': 'Способ восстановления'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_recovery_method', to='core.directory', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(blank=True, limit_choices_to={'entity_name': 'Сервисная компания'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_service_company', to='core.directory', verbose_name='Сервисная компания')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=50, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.machine')),
                ('maintenance_type', models.ForeignKey(blank=True, limit_choices_to={'entity_name': 'Вид ТО'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_type', to='core.directory', verbose_name='Вид ТО')),
                ('service_company', models.ForeignKey(blank=True, limit_choices_to={'entity_name': 'Сервисная компания'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_service_company', to='core.directory', verbose_name='Организация, проводившая ТО')),
            ],
        ),
    ]
